version: '3.4'

services:
  ProcessMonitor:
    image: ProcessMonitor:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_ProcessMonitor$
    volumes:
      - C:\Users\Admin\Documents\GitHub\camera monitor:/app
      - C:\Users\Admin\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_ProcessMonitor$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_ProcessMonitor$ bin/Debug/netcoreapp2.1/ProcessMonitor.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
